/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TestUSDC } from "./TestUSDC";
export type { WIron } from "./WIron";
export * as factories from "./factories";
export { TestUSDC__factory } from "./factories/TestUSDC__factory";
export { WIron__factory } from "./factories/WIron__factory";
